# Generated by Django 5.2.4 on 2025-07-21 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivaapp', '0002_alter_tag_name_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagForClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(max_length=250),
        ),
        migrations.AddField(
            model_name='reviews',
            name='serv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ivaapp.tagforclient'),
        ),
    ]
