# Generated by Django 5.2.4 on 2025-07-23 09:30

import appointment.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ivaapp', '0003_tagforclient_alter_reviews_text_reviews_serv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('phone', models.CharField(max_length=12, validators=[appointment.models.validate_phone])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appoinments', to='ivaapp.forclient')),
            ],
        ),
    ]
