# Generated by Django 5.2.4 on 2025-07-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_master_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
