# Generated by Django 5.2.4 on 2025-07-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_first_name_appointment_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='service',
        ),
    ]
