# Generated by Django 5.2.4 on 2025-07-25 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_appointment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointment.master'),
            preserve_default=False,
        ),
    ]
