# Generated by Django 5.2.4 on 2025-08-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_cancel_reason_appointment_cancelled_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='reschedule_date',
            new_name='rescheduled_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='reschedule_time',
            new_name='rescheduled_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reschedule_reason',
        ),
    ]
