# Generated by Django 5.2.4 on 2025-09-17 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_rename_reschedule_date_appointment_rescheduled_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создана'), ('rescheduled', 'Перенесена'), ('cancelled', 'Отменена'), ('status_changed', 'Статус изменён'), ('updated', 'Обновлена')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('client_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('master_name', models.CharField(blank=True, max_length=255, null=True)),
                ('master_telegram_id', models.CharField(blank=True, max_length=100, null=True)),
                ('old_date', models.DateTimeField(blank=True, null=True)),
                ('old_time', models.TimeField(blank=True, null=True)),
                ('new_date', models.DateTimeField(blank=True, null=True)),
                ('new_time', models.TimeField(blank=True, null=True)),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='appointment.appointment')),
            ],
        ),
    ]
